-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 23:06:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `cod_categoria` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livros` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `ano_lancamento` DATE NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `qtd_copias` INT NOT NULL,
  `categorias_cod_categoria` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_livros_categorias1_idx` (`categorias_cod_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_livros_categorias1`
    FOREIGN KEY (`categorias_cod_categoria`)
    REFERENCES `mydb`.`categorias` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livros_has_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livros_has_autores` (
  `livros_isbn` INT NOT NULL,
  `autores_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`livros_isbn`, `autores_email`),
  INDEX `fk_livros_has_autores_autores1_idx` (`autores_email` ASC) VISIBLE,
  INDEX `fk_livros_has_autores_livros_idx` (`livros_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_livros_has_autores_livros`
    FOREIGN KEY (`livros_isbn`)
    REFERENCES `mydb`.`livros` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_has_autores_autores1`
    FOREIGN KEY (`autores_email`)
    REFERENCES `mydb`.`autores` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `tipo_usuario` ENUM('Administrador', 'Bibliotecário', 'Usuário') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `cod_curso` INT NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usr_level1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usr_level1` (
  `usuarios_id` INT NOT NULL,
  INDEX `fk_usr_level1_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`usuarios_id`),
  CONSTRAINT `fk_usr_level1_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `matricula` INT NOT NULL,
  `data_de_ingresso` DATETIME NOT NULL,
  `data_de_conclusao_prevista` DATETIME NOT NULL,
  `cursos_cod_curso` INT NOT NULL,
  `usr_level1_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_alunos_cursos1_idx` (`cursos_cod_curso` ASC) VISIBLE,
  INDEX `fk_alunos_usr_level11_idx` (`usr_level1_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_cursos1`
    FOREIGN KEY (`cursos_cod_curso`)
    REFERENCES `mydb`.`cursos` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_usr_level11`
    FOREIGN KEY (`usr_level1_usuarios_id`)
    REFERENCES `mydb`.`usr_level1` (`usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  `mat_siape` INT NOT NULL,
  `regime_trabalho` ENUM('20h', '40h', 'DE') NOT NULL,
  `telefone_celular` VARCHAR(11) NOT NULL,
  `data_contratacao` DATETIME NULL,
  `cursos_cod_curso` INT NOT NULL,
  `usr_level1_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`mat_siape`),
  INDEX `fk_professores_cursos1_idx` (`cursos_cod_curso` ASC) VISIBLE,
  INDEX `fk_professores_usr_level11_idx` (`usr_level1_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_professores_cursos1`
    FOREIGN KEY (`cursos_cod_curso`)
    REFERENCES `mydb`.`cursos` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_usr_level11`
    FOREIGN KEY (`usr_level1_usuarios_id`)
    REFERENCES `mydb`.`usr_level1` (`usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `matricula` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefones` (
  `telefone` VARCHAR(11) NOT NULL,
  `funcionarios_matricula` INT NOT NULL,
  INDEX `fk_telefones_funcionarios1_idx` (`funcionarios_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_funcionarios1`
    FOREIGN KEY (`funcionarios_matricula`)
    REFERENCES `mydb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_reserva_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_reserva_livros` (
  `usuarios_id` INT NOT NULL,
  `livros_isbn` INT NOT NULL,
  `data_reserva` DATE NOT NULL,
  `data_devolucao` DATE NULL,
  PRIMARY KEY (`usuarios_id`, `livros_isbn`),
  INDEX `fk_usuarios_has_livros_livros1_idx` (`livros_isbn` ASC) VISIBLE,
  INDEX `fk_usuarios_has_livros_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_livros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_livros_livros1`
    FOREIGN KEY (`livros_isbn`)
    REFERENCES `mydb`.`livros` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefones_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefones_alunos` (
  `alunos_matricula` INT NOT NULL,
  `telefone_aluno` VARCHAR(45) NOT NULL,
  INDEX `fk_telefones_alunos_alunos1_idx` (`alunos_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_alunos_alunos1`
    FOREIGN KEY (`alunos_matricula`)
    REFERENCES `mydb`.`alunos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`viewLivros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viewLivros` (`titulo` INT, `ano_lancamento` INT, `editora` INT, `descricao` INT, `nome` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`viewProfessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viewProfessor` (`usr_level1_usuarios_id` INT, `id` INT, `nome` INT, `nome_curso` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`viewReservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viewReservas` (`titulo` INT, `isbn` INT, `nome` INT, `data_reserva` INT, `data_devolucao` INT);

-- -----------------------------------------------------
-- View `mydb`.`viewLivros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`viewLivros`;
USE `mydb`;
CREATE  OR REPLACE VIEW `viewLivros` AS
    SELECT 
        l.titulo, l.ano_lancamento, l.editora, c.descricao, a.nome
    FROM
        livros l
            JOIN
        categorias c ON l.categorias_cod_categoria = c.cod_categoria
            JOIN
        livros_has_autores lha ON lha.livros_isbn = l.isbn
            JOIN
        autores a ON lha.autores_email = a.email
    ORDER BY c.cod_categoria , l.editora , l.ano_lancamento , a.nome;

-- -----------------------------------------------------
-- View `mydb`.`viewProfessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`viewProfessor`;
USE `mydb`;
CREATE  OR REPLACE VIEW `viewProfessor` AS
    SELECT 
        p.usr_level1_usuarios_id, u.id, u.nome, c.nome_curso
    FROM
        professores p
            JOIN
        usuarios u ON u.id = p.usr_level1_usuarios_id
            JOIN
        cursos c ON p.cursos_cod_curso = c.cod_curso
    ORDER BY c.nome_curso;

-- -----------------------------------------------------
-- View `mydb`.`viewReservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`viewReservas`;
USE `mydb`;
CREATE  OR REPLACE VIEW `viewReservas` AS
    SELECT 
        l.titulo, l.isbn, u.nome, ur.data_reserva, ur.data_devolucao
    FROM
        livros l
            JOIN
        usuarios_reserva_livros ur ON l.isbn = ur.livros_isbn
            JOIN
        usuarios u ON ur.usuarios_id = u.id;
USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`alunos_BEFORE_INSERT` BEFORE INSERT ON `alunos` FOR EACH ROW
BEGIN
	if(new.data_de_conclusao_prevista > current_timestamp())
		then 
		insert into 
			alunos(matricula, data_de_ingresso, data_de_conclusao_prevista, cursos_cod_curso, usr_level1_usuarios_id) 
			values(new.matricula, new.data_de_ingresso, new.data_de_conclusao_prevista, new.cursos_cod_curso, new.usr_level1_usuarios_id); 
    end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`usuarios` (`id`, `nome`, `endereco`, `login`, `senha`, `tipo_usuario`) VALUES (1, 'lucas', 'rua teste', 'lucas@ufc.br', '12345678', 'Administrador');

COMMIT;

